name: Flutter Web
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build Web
    env:
      my_secret: $
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'
      - run: flutter pub get
      - run: flutter config --enable-web
      # - run: flutter build web --web-renderer canvaskit --base-href "/${{ github.event.repository.name }}/"
      - run: flutter build web  --web-renderer html --base-href "/${{ github.event.repository.name }}/"
      
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git --work-tree build/web add --all
      - run: git commit -m "Automatic deployment by github-actions"
      - run: git push origin HEAD:gh_pages --force